- name: Install Nginx
  yum:
    name: nginx
    state: installed

#- name: Download the code
#  get_url:
#    url: https://github.com/roboshop-devops-project/frontend/archive/main.zip
#    dest: /tmp
#
## rm -rf frontend-master static
## mv localhost.conf /etc/nginx/default.d/roboshop.conf
#
#- name: Remove old contetnt
#  file:
#    path: /usr/share/nginx/html
#    state: absent
#- name: unzip the acrchive
#  unarchive:
#    src: /tmp/frontend-main.zip
#    dest: /tmp
#    remote_src: yes
#- name: remove the files
#  copy:
#    src: /tmp/frontend-main/static/
#    dest: /usr/share/nginx/html
#    remote_src: yes
#- name: copy config file
#  copy:
#    src: roboshop.conf
#    dest: /etc/nginx/default.d/roboshop.conf

- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes


