- name: Install Nginx
  yum:
    name: nginx
    state: installed

- name : Download the code
  include_role:
    name: common
    tasks_from: download

- name: Remove old contetnt
  file:
    path: /usr/share/nginx/html
    state: absent

- name: remove the files
  copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html
    remote_src: yes
- name: copy config file
  copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes


