- name: Install Nginx
  become: yes
  yum:
    name: nginx
    state: installed

- name: Download the code
  get_url:
    url: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp