- name: Setup mongodb repo
  copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install Mongodb
  yum:
    name : mongodb-org
    state: present

- name: Update the Listen IP
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start Mongodb
  systemd:
    name : mongod
    state: started
    enabled: yes

- name : Download the code
  unarchive:
    src: https://github.com/roboshop-devops-project/mongodb/archive/main.zip
    dest: /tmp/
    remote_src: yes

- name : Load the schema
  mongodb_shell:
    file: "/tmp/mongodb-main/catalogue.js"
    idempotent: yes

- name : Load the schema
  mongodb_shell:
    file: "/tmp/mongodb-main/users.js"
    idempotent: yes