- name : Demo var
  hosts: all
  vars:
    URL: google.com
  tasks:
    - name: print variable
      debug:
        msg: "URL = {{URL}}"
    - name: task level var
      vars:
       URL: task.google.com
      debug:
        msg: "task URL = {{URL}}"

- name: Demo on variables
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: Print a Variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"
    - name: Print task Variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"
      vars:
        URL: task1.google.com