- name: Demo on register
  hosts: all
  tasks:
    - name: Run uptime command
      shell: uptime
      register: output
    - name: set a fact
      set_fact:
        uptime: "{{output.stdout}}"

    - name: print output
      debug:
        msg: "{{uptime}}"
