- name : User creation
  user:
    name : roboshop

- name: Download from Github
  include_tasks:
    file: download-from-git.yml

- name : Delete the old code
  file :
    path : /home/roboshop/{{COMPONENT}}
    state : absent

- name : Install the code
  copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
    owner : roboshop
    group : roboshop