- name : Install nodejs
  yum :
    name : ["nodejs","nodejs","gcc-c++"]
    state: installed

- name : User creation
  user:
    name : roboshop
    state : present

- name : Code Download
  include_role:
    name : common
    tasks_from : download

- name : Install the code
  copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONEN}}/
    remote_src: yes
    owner : roboshop
    group : roboshop

- name : Install NPM
  become_user: roboshop
  npm:
    path: /home/roboshop/{{COMPONENT}}
    state : latest

- name : Update systemd config
  copy:
    src : systemd.service
    dest : /etc/systemd/system/{{COMPONENT}}.service

- name : Restart catalogue service
  systemd:
    name: "{{COMPONENT}}"
    state: started
    enabled: yes
    daemon_reload: yes
