- name : Install nodejs
  yum :
    name : ["nodejs","nodejs","gcc-c++"]
    state: installed

- name : Code Download
  include_role:
    name : common
    tasks_from : download

- name : Install NPM
  become_user: roboshop
  npm:
    path: /home/roboshop/{{COMPONENT}}
    state : latest

- name : Systemd setup
  include_tasks :
    file : systemd.yml