- name : Update systemd config
  template:
    src : systemd.service
    dest : /etc/systemd/system/{{COMPONENT}}.service
  notify : Restart service - Handler

- name : Restart service
  systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes