- name: Mysql repo setup
  copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name : Installing Mysql
  yum:
    name : ["mysql-community-server", "MySQL-python"]
    state: present

- name : Start the mysqld
  systemd :
    name : mysqld
    state : restarted
    enabled : yes

- name : Default mysql password
  shell : grep "temporary password" /var/log/mysqld.log|awk '{print $NF}'
  register: out

- name : Change default password
  shell : echo "show databases;" | mysql -uroot -pRoboShop@1
  register : defalu_pass
  ignore_errors : yes
