- name: Mysql repo setup
  copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name : Installing Mysql
  yum:
    name : ["mysql-community-server", "MySQL-python"]
    state: present

- name : Start the mysqld
  systemd :
    name : mysqld
    state : restarted
    enabled : yes

- name : Default mysql password
  shell : grep "temporary password" /var/log/mysqld.log|awk '{print $NF}'
  register: out

- name: Check the default password
  community.mysql.mysql_query:
    query: show databases
    login_password: RoboShop@1
    login_user: root
  register: default_mysql_check
  ignore_errors: yes

- name : print password
  when : default_mysql_check.failed
  shell: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'RoboShop@1';" | mysql --connect-expired-password -uroot -p"{{out.stdout}}"

- name: Uninstall validate plugin
  community.mysql.mysql_query:
    query: uninstall plugin validate_password
    login_password: RoboShop@1
    login_user: root