- name : Configure redis repo
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Install redis
  yum:
    name: redis
    enablerepo: remi
    state: present

- name: Update the BindIP in config file
  replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start the redis service
  systemd:
    name: redis
    state: restarted
    enabled: yes